### PR TITLE
[WIP] Fix tests and make Travis-CI work

### PR DESCRIPTION
**Pull request by wbushey**
Goal is to have all written tests pass, and to add a Travis-CI file to run CI on 2.x rubies

### CODE REVIEW

**Comment by wbushey** [comment]
Currently at 14 failing tests

**Comment by chadfennell** [comment]
Hey Bill, I'll be pushing a PR tonight to upgrade the site to Rails 4. I went ahead and fixed and refactored broken tests as part of that process: https://github.com/campuscodefest/ccf/commits/rails4. You might want to hold off until that has been merged back in. There is lots of room for improvement in our test coverage overall...

and thank you very much for digging into this!

**Comment by wbushey** [comment]
Thanks for the update @chadfennell; that's great to hear. I'll hold off on the rest of the tests, and leave this PR hanging out for now.

**Comment by wbushey** [comment]
This has also been rebased to include the Rails 4 upgrade. I'm still seeing two failing tests, both in spec/helpers/comment_mailer_helper. 

One might be an actual mismatch between expectations and existing logic. The "[sends an emails when email alerts are enabled for everyone](https://github.com/campuscodefest/ccf/blob/9ffb37c334b01a5efbc399ef9057f538b0958d92/spec/helpers/comment_mailer_helper_spec.rb#L5)" is expecting CommentMailerHelper.get_project_users to return two users. But, [CommentMailerHelper.get_project_users will return only the project owner if the project owner has notifications turned on](https://github.com/campuscodefest/ccf/blob/9ffb37c334b01a5efbc399ef9057f538b0958d92/app/helpers/comment_mailer_helper.rb#L3).

The other failing test is frustrating to debug, and I suspect has something to do with the way FactoryGirl handles has_many through relationships, though it also related to CommentMailerHelper.get_project_users. ["sends an emails when email alerts are enabled only for commenters"](https://github.com/campuscodefest/ccf/blob/9ffb37c334b01a5efbc399ef9057f538b0958d92/spec/helpers/comment_mailer_helper_spec.rb#L26) is expecting an array with one user, but CommentMailerHelper.get_project_users is returning an empty array. That array is empty because User.project_notifiable relies on User.commented_projects, which relies on User.project_comments. User.project_comments is being populated with a ProjectComment that has a project_id, but for some reason, calling `project` on that ProjectComment returns nil.

This is what happens if I throw a binding.pry into that test and do the following:

```ruby
a_project = project(project_owner, comment_user)
=> #<Project:0x007fb4172c8030>
a_project.comments.first.project
=> #<Project:0x007fb4172c8030>
a_project.comments.first.user
=> #<User:0x007fb4171e01b8>
a_project.comments.first.user.project_comments.first
=> #<ProjectComment:0x007fb4172a4450>
a_project.comments.first.user.project_comments.first.project
=> nil
a_project.comments.first.user.commented_projects
=> []
comment_user
=> #<User:0x007fb4171e01b8>
comment_user.project_comments.first
=> #<ProjectComment:0x007fb4172613d0>
comment_user.project_comments.first.project
=> nil
comment_user.commented_projects
=> []
```

**Comment by wbushey** [comment]
Woohoo, Travis is working as it should. Tests are running, and failures are real failures.

**Comment by pete2786** [comment]
Awesome!!!!

--
David E H Peterson
pete2786.github.io

Responding via phone.

**Comment by chadfennell** [comment]
Bang! Nice.

**Comment by chadfennell** [comment]
Ah, yeah, I hadn't rebased the comment refactor. Just pulled down this change and get the same failure. I hope to spend some time on the CCF app later. Thanks for the heads-up!

**Comment by pete2786** [comment]
Going to merge this so we can get travis config in master.

**Pull request merged**
